#!/bin/bash
# Start varnish and log
echo -e "\nStarting Varnish\n"
varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:${VARNISH_PORT}
echo -e "\nVarnish Started\n"
sleep 15
echo -e "\nOpen Logs\n"
varnishlog